declare const Icon: import("react").FC<import("react-native").TextProps & {
    name: "archive" | "arrow-down" | "arrow-left" | "arrow-right" | "arrow-up" | "bell" | "calendar" | "camera" | "cart" | "chart" | "check" | "chevron-down" | "chevron-left" | "chevron-right" | "chevron-up" | "clock" | "close" | "close-o" | "comment" | "credit-card" | "envelope" | "exclamation" | "external-link" | "eye" | "gear" | "heart" | "image" | "like" | "link" | "location" | "lock" | "minus" | "navicon" | "paperclip" | "pencil" | "play" | "plus" | "pointer" | "question" | "redo" | "refresh" | "retweet" | "sc-facebook" | "sc-github" | "sc-google-plus" | "sc-instagram" | "sc-linkedin" | "sc-odnoklassniki" | "sc-pinterest" | "sc-skype" | "sc-soundcloud" | "sc-telegram" | "sc-tumblr" | "sc-twitter" | "sc-vimeo" | "sc-vk" | "sc-youtube" | "search" | "share-apple" | "share-google" | "spinner" | "spinner-2" | "spinner-3" | "star" | "tag" | "trash" | "trophy" | "undo" | "unlock" | "user";
    size?: number;
    color?: import("react-native").TextStyle["color"];
    innerRef?: import("react").Ref<import("react-native").Text>;
} & import("react").RefAttributes<import("react-native").Text>> & {
    getImageSource: (name: "archive" | "arrow-down" | "arrow-left" | "arrow-right" | "arrow-up" | "bell" | "calendar" | "camera" | "cart" | "chart" | "check" | "chevron-down" | "chevron-left" | "chevron-right" | "chevron-up" | "clock" | "close" | "close-o" | "comment" | "credit-card" | "envelope" | "exclamation" | "external-link" | "eye" | "gear" | "heart" | "image" | "like" | "link" | "location" | "lock" | "minus" | "navicon" | "paperclip" | "pencil" | "play" | "plus" | "pointer" | "question" | "redo" | "refresh" | "retweet" | "sc-facebook" | "sc-github" | "sc-google-plus" | "sc-instagram" | "sc-linkedin" | "sc-odnoklassniki" | "sc-pinterest" | "sc-skype" | "sc-soundcloud" | "sc-telegram" | "sc-tumblr" | "sc-twitter" | "sc-vimeo" | "sc-vk" | "sc-youtube" | "search" | "share-apple" | "share-google" | "spinner" | "spinner-2" | "spinner-3" | "star" | "tag" | "trash" | "trophy" | "undo" | "unlock" | "user", size?: number, color?: import("react-native").TextStyle["color"]) => Promise<{
        uri: string;
        scale: number;
    } | undefined>;
    getImageSourceSync: (name: "archive" | "arrow-down" | "arrow-left" | "arrow-right" | "arrow-up" | "bell" | "calendar" | "camera" | "cart" | "chart" | "check" | "chevron-down" | "chevron-left" | "chevron-right" | "chevron-up" | "clock" | "close" | "close-o" | "comment" | "credit-card" | "envelope" | "exclamation" | "external-link" | "eye" | "gear" | "heart" | "image" | "like" | "link" | "location" | "lock" | "minus" | "navicon" | "paperclip" | "pencil" | "play" | "plus" | "pointer" | "question" | "redo" | "refresh" | "retweet" | "sc-facebook" | "sc-github" | "sc-google-plus" | "sc-instagram" | "sc-linkedin" | "sc-odnoklassniki" | "sc-pinterest" | "sc-skype" | "sc-soundcloud" | "sc-telegram" | "sc-tumblr" | "sc-twitter" | "sc-vimeo" | "sc-vk" | "sc-youtube" | "search" | "share-apple" | "share-google" | "spinner" | "spinner-2" | "spinner-3" | "star" | "tag" | "trash" | "trophy" | "undo" | "unlock" | "user", size?: number, color?: import("react-native").TextStyle["color"]) => {
        uri: string;
        scale: number;
    } | undefined;
};
export default Icon;
//# sourceMappingURL=index.d.ts.map